<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel='stylesheet' type='text/css' href='../public/style/normalize.css'>
    <link rel='stylesheet' type='text/css' href='../public/style/style.css'>
    <title>Bens Todo App</title>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="mx-auto" style="width: 200px;">
                <form method="POST" action="/add">
                    <textarea name="addTask"></textarea>
                    <select class="dropDown" name="chooseTodo">
                        <?php
                        foreach($todoLists as $task) {
                            echo '<option value=' . $task["id"] . '>' . $task["to_do_list"] . '</option>';
                        } ?>
                    </select>
                    <input type="submit">
                </form>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-6">
                <h1>Dog Related Todo List</h1>
                <?php
                foreach ($tasks as $task) {
                    if($task["list_selection"] == 1)
                        echo '<p>' . $task["task"] .
                            '<form method="POST" action="/remove">
              <input type="hidden" name="removeTask" value="' . $task["id"] . '">
              <input type="submit" value="Completed">
              </form>' . '</p>';
                } ?>
            </div>
            <div class="col-6">
                <h1>Other Todo List</h1>
                <?php
                foreach ($tasks as $task) {
                    if($task["list_selection"] == 2)
                        echo '<p>' . $task["task"] .
                            '<form method="POST" action="/remove">
              <input type="hidden" name="removeTask" value="' . $task["id"] . '">
              <input type="submit" value="Completed">
              </form>' . '</p>';
                } ?>
            </div>
        </div>
    </div>
</body>
</html>