<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel='stylesheet' type='text/css' href='../public/style/normalize.css'>
    <link rel='stylesheet' type='text/css' href='../public/style/style.css'>
    <title>Bens Todo App</title>
</head>

<body>
    <h1>My Todo List</h1>
    <?php
    foreach ($tasks as $task) {
        echo '<p>' . $task["task"] . '</p>';
        echo '<form method="POST" action="/remove">
              <input type="hidden" name="removeTask" value="' . $task["id"] . '">
              <input type="submit" value="Completed">
              </form>';
    } ?>
    <form method="POST" action="/add">
        <textarea name="addTask"></textarea>
        <input type="submit">
    </form>
</body>
</html>